AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false


Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/*
Style/StringLiterals:
  Exclude:
    - db/schema.rb
Style/SymbolProc:
  Exclude:
    - app/serializers/*