version: '3'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: my_store_development
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: ILoveDoingKnowBe4Training!
    ports:
      - "5432:5432"
    networks:
      - railsnetwork

  myapp-web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: my_store_development
      DB_USERNAME: my_user
      DB_PASSWORD: ILoveDoingKnowBe4Training!
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - railsnetwork
volumes:
  postgres_data: {}
networks:
  railsnetwork:
     driver: bridge