version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: my_store_development
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: ILoveDoingKnowBe4Training!
    ports:
      - "5432:5432"
    networks:
      - railsnetwork

  myapp-web:
    build: .
    command: "bundle exec rails s -b '0.0.0.0'"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: my_store_development
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: ILoveDoingKnowBe4Training!
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - railsnetwork
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/frontend:cached
    ports:
      - "3001:3000"
    environment:
      - HOST=0.0.0.0
    networks:
      - railsnetwork

volumes:
  postgres_data: {}

networks:
  railsnetwork:
    driver: bridge
