---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/current_user":
    get:
      summary: list current_users
      responses:
        '200':
          description: successful
  "/api/type_products":
    get:
      summary: list type_products
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
    prodHost:
      default: my-site.com
